# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'GetStreamExample' do
  use_frameworks!
  
  pod 'GetStream', :path => '../'
  
  target 'GetStreamExampleTests' do
    inherit! :search_paths
  end
  
end
