# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'GetStreamExample' do
  use_frameworks!
  pod 'GetStream', :path => '..'
  pod 'SwiftyJWT'
end

# For Swift 4.0 pods.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'SwiftyCrypto' && target.name == 'SwiftyJWT'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
