# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'GetStreamExample' do
  use_frameworks!
  pod 'GetStream', :path => '..'
  pod 'GetStream/Token', :path => '..'
  pod 'Faye', :path => '..'
end

# For Swift 4.0 pods.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'JSONWebToken'
      system("rm -rf Pods/JSONWebToken/CommonCrypto")
    end
  end
end

install! 'cocoapods', :disable_input_output_paths => true
