# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

carthage(use_binaries: false, platform: "iOS", cache_builds: true, new_resolver: true)

default_platform(:ios)

platform :ios do
  desc "Run all unit tests for GetStream"
  lane :tests do
    run_tests(scheme: "GetStream-iOS")
  end
end
